nav:
  Home: /
  About: /about/
  Archive: /archives/
  Book: /book/
  'Cultural Life': /cultural-life/
  Projects: http://github.com/originerd

projects_url: http://github.com/originerd

customize:
    gravatar:
        email: originerd@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: true
    favicon: 
      desktop:
        url: /images/favicon.png
        gravatar: false
      android:
        url: /images/favicon.png
        gravator: false
      apple:
        url: /images/favicon.png
        gravator: false
    social_links:
        github: http://github.com/originerd
        twitter: https://twitter.com/Originerds
        facebook: https://www.facebook.com/originerd
        linkedin: https://www.linkedin.com/in/originerd
    post_count: 12
    highlight: rainbow

# RSS
rss: atom.xml

# Plugins
plugins:
    disqus_shortname: originerd
    google_analytics: UA-90669451-1

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
